# Server settings
server.port=8080
server.servlet.context-path=/api

# Application name
spring.application.name=testTaskJustAI

# Task execution pool
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=500

# Cache
spring.cache.type=simple

# VK API Settings
vk.api.token=your_token
vk.api.version=5.131
vk.api.base-url=https://api.vk.com/method

# VK Bot Settings
vk.bot.confirmation-code=your_code
vk.bot.group-id=123456